
services:
  recipebook_db:
    image: postgres
    container_name: recipebook_db
    restart: always
    environment:
      POSTGRES_USER: recipeadmin
      POSTGRES_PASSWORD: 1q2w3e4r
      POSTGRES_DB: recipebookdb
    ports:
      - "5432:5432"
    networks:
      - food_network
    volumes:
      - recipebook_vol:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  recipebook_app:
    build: .
    container_name: Recipe_book
    ports:
      - "3000:3000"
    networks:
      - food_network
    depends_on:
      - recipebook_db

networks:
  food_network:

volumes:
  recipebook_vol:
